version: '3.8'

services:
  business-card-preprepress:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/Business-Card-Prepress/uploads
      - ./output:/app/Business-Card-Prepress/output
      - ./logs:/app/Business-Card-Prepress/logs
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=your-production-secret-key-change-this
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3